version: "3.8"

services:
  nextjs:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development} # Default to development if NODE_ENV is not set
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - S3_BUCKET=my-bucket
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ]; then npm run start; else npm run dev; fi"
    depends_on:
      - pocketbase
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../package.json:/app/package.json
      - ../pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ../tsconfig.json:/app/tsconfig.json
      - ../next-env-d.ts:/app/next-env-d.ts
      - ../next.config.mjs:/app/next.config.mjs
      - ../potscss.config.cjs:/app/potscss.config.cjs
    networks:
      - app-network

  pocketbase:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile.pocketbase
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase_data:/pb/pb_data
    networks:
      - app-network
    # command: ["serve", "--dir", "/pb_data"]

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
